### ISSUE TITLE
Rendering Thread Exception on play if camera isn't available

### ISSUE THREAD

**Issue by Caffiendish** [Rectus/UE4SteamVRPassthrough#1]
If the camera isn't available (~~Too often~~ _Sometimes_ the eTronVideo device just doesn't feel like working), the following exception is thrown:

> Fatal error: [File:D:/Build/++UE4/Sync/Engine/Source/Runtime/RenderCore/Private/RenderingThread.cpp] [Line: 902] 
> Rendering thread exception:
> Assertion failed: SizeX > 0 && SizeY > 0 && NumMips > 0 [File:D:/Build/++UE4/Sync/Engine/Source/Runtime/Windows/D3D11RHI/Private/D3D11Texture.cpp] [Line: 561] 
> 
> 
> 
> 0x00007ff9db1c4f69 KERNELBASE.dll!UnknownFunction []
> 0x00007ff9554b0216 UE4Editor-Core.dll!UnknownFunction []
> 0x00007ff9554b4218 UE4Editor-Core.dll!UnknownFunction []
> 0x00007ff9551d242d UE4Editor-Core.dll!UnknownFunction []
> 0x00007ff955126a45 UE4Editor-Core.dll!UnknownFunction []
> 0x00007ff9551280a0 UE4Editor-Core.dll!UnknownFunction []
> 0x00007ff93b337d4c UE4Editor-D3D11RHI.dll!UnknownFunction []
> 0x00007ff93b37e096 UE4Editor-D3D11RHI.dll!UnknownFunction []
> 0x00007ff937dd8061 UE4Editor-SteamVRPassthrough.dll!FSteamVRExternalTextureResource::InitRHI() [E:\Projects\Source\Git\UE4SteamVRPassthrough_Example\Plugins\SteamVRPassthrough\Source\SteamVRPassthrough\Private\SteamVRExternalTexture.cpp:119]
> 0x00007ff9b123e35b UE4Editor-RenderCore.dll!UnknownFunction []
> 0x00007ff9b1277db4 UE4Editor-RenderCore.dll!UnknownFunction []
> 0x00007ff9b12828f9 UE4Editor-RenderCore.dll!UnknownFunction []
> 0x00007ff954f32398 UE4Editor-Core.dll!UnknownFunction []
> 0x00007ff954f327ce UE4Editor-Core.dll!UnknownFunction []
> 0x00007ff9b1209c67 UE4Editor-RenderCore.dll!UnknownFunction []
> 0x00007ff9b1212f34 UE4Editor-RenderCore.dll!UnknownFunction []
> 0x00007ff9554cff0b UE4Editor-Core.dll!UnknownFunction []
> 0x00007ff9554c7050 UE4Editor-Core.dll!UnknownFunction []
> 0x00007ff9dd627034 KERNEL32.DLL!UnknownFunction []
> 0x00007ff9dd762651 ntdll.dll!UnknownFunction []

It kills off the editor if I don't use standalone mode, which is a bit of an issue.
Perhaps a check for the asserted values before pressing ahead is an option?

Having gotten the project to run though, this is some _amazing_ work, and something I've been considering/wishing for, ever since Valve showed us passthrough, so thanks a lot for sharing it! (Consider posting to the UE subreddit!)

**Comment by Rectus** [comment]
I updated the plugin with checks for the texture size. It should now fail to initialize the video instead of crashing. I couldn't coax the camera device to break on my end, so I haven't been able to verify if the changes help.

Thanks for using the plugin BTW, and reporting the issue!

**Comment by Caffiendish** [comment]
I could only reproduce by turning the camera off in the Steam VR settings, after I got it working, will test when I get a moment.

**Comment by Caffiendish** [comment]
Yep, fix works just fine! Looking through the orbs gives me an interesting grid view.
Thanks for the prompt fix!
