### ISSUE TITLE
UE5 Update

### ISSUE THREAD

**Issue by Dominique57** [Rectus/UE4SteamVRPassthrough#3]
Hi,

During the developement of a simulator we wanted to make a passthrough for a IPad-like tablet.
I stumbled upon your repository however is for UE 4.26 or 4.27 only, and we are working on ue5.
I managed to update the plugin to ue5 (there has been some struct-api changes, shader-parameters errors, etc...).

However if the sphere passthrough seems to be working fine, when I press the trigger the left eye seems to be completly distorted.
Also i didn't tested with the 4.27 but with the Vive pro 2 there seems to be an offset between hmd and vr position.

(My) bugs aside I was wondering if you would be interested in having a PR to create a ue5-version branch for your plugin ?

**Comment by Rectus** [comment]
Oh, please do. I've been thinking about upgrading it for UE5, but haven't had the time yet.

I'll check it out and see if it works for my headsets. Unfortunately I don't have a Vive Pro 2, so I don't know if it works on the 4.27 version either.

**Comment by Rectus** [comment]
The UE5 version is now at https://github.com/Rectus/UE4SteamVRPassthrough/tree/ue5, see the pull request for more details.

**Comment by Dominique57** [comment]
Hi,

I can indeed confirm it works with the Vive pro 2 using unreal engine 5.0.0.
Thanks a lot for the fix, I definitely didn't expect the static_cast to mess everything up.

Have a good one !
