### ISSUE TITLE
Vive Focus 3 Support

### ISSUE THREAD

**Issue by MrVinceZ** [Rectus/UE4SteamVRPassthrough#6]
**Describe the bug**
The passthrough doesn't work on the Example Project with a Vive Focus 3

**LOG**
```
LogSteamVRPassthrough: Initializing SteamVR camera passthrough.
LogSteamVRPassthrough: Warning: CameraFrameSize error [100] on device Id 0
LogSteamVRPassthrough: Warning: Error enabling passthrough video!
LogSteamVRPassthrough: Warning: GetTrackedCameraEyePoses error [4]
```

**To Reproduce**
1. Connect the Vive Focus 3 via Vive Business Streaming
2. Make sure SteamVR is on
3. Launch the VR Preview on UE 4.27

**Expected behavior**
Passthrough working on the orb or via PP Material

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Unreal 4.27
 - Project Passthrough Example
 - Vive Focus 3

**Additional context**
I see that the function EnableVideo return false, Same for the function "Has Camera"

Thank you

**Comment by Rectus** [comment]
Unfortunately I don't think the Vive Focus provides access to the camera. Does it work with the SteamVR room view?

**Comment by MrVinceZ** [comment]
Yes, this view ? 
![Screenshot_20230330_215333 1](https://user-images.githubusercontent.com/38558569/228949999-91af6043-1cc8-4e05-b32e-94f57f02c1b5.png)

**Comment by MrVinceZ** [comment]
After digging a little, I found this topic : https://forum.htc.com/topic/12743-updatewave-450-demonstration-on-how-to-use-wave-passthrough-underlayoverlay-apis/

Maybe it can help ?

**Comment by Rectus** [comment]
I mean the passthrough feature in the SteamVR compositor. If it is available, the SteamVR settings will have something like this available:
![bild](https://user-images.githubusercontent.com/4642151/228953200-b81751cf-6139-4962-86b3-e079f92cdb99.png)

According to that link though, HTC does not provide access to the actual passthrough images, which means this passthrough plugin will not work.

**Comment by MrVinceZ** [comment]
Hello, I confirm that I do not have access to the "Camera" setting

On the link given, it is indicated that the API is indeed available for the vive 3, but that nothing is exposed directly blueprint (see https://forum.htc.com/topic/12743-updatewave-450-demonstration-on-how-to-use-wave-passthrough-underlayoverlay-apis/?do=findComment&comment=48137 ) 

Moreover, a Unity project is provided as an example ( https://github.com/hardcoded2/WavePassthroughOverlayExample ) . 

Thanks again for your time!

**Comment by Rectus** [comment]
Thanks for checking it. Unfortunately the Wave API is runtime composition based, which is out of scope for this plugin. The plugin is built around the idea of compositing the camera output directly in the application, as SteamVR does not support runtime based composition.

According to the documentation the Wave SDK does have a blueprint function library with the passthrough functions:
https://hub.vive.com/storage/app/doc/en-us/UnrealPlugin/UnrealDocBlueprintFunctionLibrary.html

There also seems to be a plugin available for the Vive OpenXR extensions:
https://developer.vive.com/resources/openxr/openxr-mobile/overview/

Note that neither of these seem to support PCVR applications. Likely the Focus 3 itself only supports passthrough with mobile applications.

Closing this issue, as it's out of scope.
